---
title: "CFSS Homework 03"
author: "Cory J. Cascalheira"
date: "December 21, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Part 1
___
Load dependencies.

```{r message=FALSE}
library(tidyverse)
library(readxl)
```

Load the data.

```{r}
load("J:/sample_data/dadmom.rda")
dadmom
```

Tidy the data frame.

```{r}
# Tidy parents and names
(parents <- dadmom %>%
  # Remove income columns
  select(-starts_with("inc")) %>%
  # Gather except family ID
  gather(key = parent, value = name, -famid) %>%
  # Make parent variable make more sense
  mutate(parent = fct_recode(factor(parent), "father" = "named", "mother" = "namem"))
)

# Tidy the income, make sure order matches parents
(income <- dadmom %>%
  # Remove name columns
  select(-starts_with("name")) %>%
  # Gather except family ID
  gather(key = parent, value = income, -famid) %>%
  # Drop family ID and parent columns
  select(income)
)

# Bind columns
(dadmom_new <- bind_cols(parents, income)
)
```

# Part 2
___
Load the data.

```{r}
library(gapminder)
hiv <- read_excel("J:/sample_data/hiv-prevalence.xlsx")
hiv
```

Fix the country column.

```{r}
colnames(hiv)[1] <- "country"
```

Are the same countries in both datasets?

```{r}
# Which countries are in the gapminder dataset
gapminder_names <- unique(as.character(gapminder$country))

# Filter the HIV dataset to include only those countries in gapminder
(hiv2 <- hiv %>%
  filter(country %in% gapminder_names)
)
```

Tidy the HIV data frame.

```{r}
(hiv3 <- hiv2 %>%
  gather(key = year, value = hiv_prevalence, -country)
)
```

Transform year variable into an integer.

```{r}
hiv3$year <- as.integer(hiv3$year)

# Verify change
head(hiv3)
```

## HIV Prevalence & Life Expectancy

```{r}

```


# Part 3
___
